# multidms

## Overview of model

The `multidms` model applies to a case where you have DMS datasets for two or more homologs and are interested in identifying shifts in mutational effects between homologs.
To do so, the model defines one homolog as a reference homolog.
For each mutation, the model fits one parameter that quantifies the effect of the mutation in the reference homolog.
For each non-reference homolog, it also fits a shift parameter that quantifies the shift in the mutation's effect in the non-reference homolog relative to the reference.
Shift parameters can be regularized, encouraging most of them to be close to zero.
This regularization step is a useful way to eliminate the effects of experimental noise, and is most useful in cases where you expect most mutations to have the same effects between homologs, such as for homologs that are close relatives.

The model uses a global-epistasis function to disentangle the effects of multiple mutations on the same variant.
To do so, it assumes that mutational effects additively influence a latent biophysical property the protein (e.g., $\Delta G$ of folding).
The mutational-effect parameters described above operate at this latent level.
The global-epistasis function then assumes a sigmoidal relationship between a protein's latent property and its functional score measured in the experiment (e.g., log enrichment score).
Ultimately, mutational parameters, as well as ones controlling the shape of the sigmoid, are all jointly fit to maximize agreement between predicted and observed functional scores acorss all variants of all homologs.

## Detailed description of the model

For each variant $v$ from homolog $h$, we use a global-epistasis function $g$ to convert a latent phenotype $\phi$ to a functional score $f$:

$$f(v,h) = g_{\alpha}(\phi(v,h))$$

where $g$ is a sigmoid and $\alpha$ is a set of parameters encoding the sigmoid.

The latent phenotype is computed in the following way:

$$\phi(v,h) = c + \sum_{m \in v} (x_m + s_{m,h})$$

where:
* $c$ is the wildtype latent phenotype for the reference homolog.
* $x_m$ is the latent phenotypic effect of mutation $m$. See details below.
* $s_{m,h}$ is the shift of the effect of mutation $m$ in homolog $h$. These parameters are fixed to zero for the reference homolog. For non-reference homologs, they are defined in the same way as $x_m$ parameters.
* $v$ is the set of all mutations relative to the reference wildtype sequence (including all mutations that separate homolog $h$ from the reference homolog).

The $x_m$ variable is defined such that mutations are always relative to the reference homolog.
For example, if the wildtype amino acid at site 30 is an A in the reference homolog, and a G in a non-reference homolog, then a Y30G mutation in the non-reference homolog is recorded as an A30G mutation relative to the reference.
This way, each homolog informs the exact same parameters, even at sites that differ in wildtype amino acid.
These are encoded in a `BinaryMap` object, where all sites that are non-identical to the reference are 1's.

Ultimately, we fit parameters using a loss function with one term that scores differences between predicted and observed values and another that uses L1 regularization to penalize non-zero $s_{m,h}$ values:

$$ L_{\text{total}} = \sum_{h} \left[\sum_{v} L_{\text{fit}}(y_{v,h}, f(v,h)) + \lambda \sum_{m} |s_{m,h}|\right]$$

where:
* $L_{\text{total}}$ is the total loss function.
* $L_{\text{fit}}$ is a loss function that penalizes differences in predicted vs. observed functional scores.
* $y_{v,h}$ is the experimentally measured functional score of variant $v$ from homolog $h$.

## Model using matrix algebra

We compute a vector or predicted latent phenotypes $P_{h}$ as:

$$P_{h} = c + (X_h \cdot (β + S_h))$$

where:
* $β$ is a vector of all $β_m$ values.
* $S_h$ is a matrix of all $s_{m,h}$ values.
* $X_h$ is a sparse matrix, where rows are variants, columns are mutations (all defined relative to the reference homolog), and values are weights of 0's and 1's. These weights are used to compute the phenotype of each variant given the mutations present.
* $c$ is the same as above.

In the matrix algebra, the sum of $β_m$ and $S_{m,h}$ gives a vector of mutational effects, with one entry per mutation.
Multiplying the matrix $X_h$ by this vector gives a new vector with one entry per variant, where values are the sum of mutational effects, weighted by the variant-specific weights in $X_h$.
Adding the $c$ value to this vector will give a vector of predicted latent phenotypes for each variant.

Next, the global-epistasis function can be used to convert a vector of predicted latent phenotypes to a vector of predicted functional scores.

$$F_{h,pred} = g_{\alpha}(P_h)$$

Finally, this vector could be fed into a loss function and compared with a vector of observed functional scores.

## Import `Python` modules

In [10]:
import pandas as pd
import numpy as np
import re
import binarymap as bmap

import matplotlib.pyplot as plt
import seaborn as sns
import jax
jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp
from jax.experimental import sparse
import jaxopt
import numpy as onp
from scipy.stats import pearsonr

## Strategy for converting mutations to be relative to the reference homolog

As described above, our strategy involves converting all mutations in all homologs to be relative to the amino-acid sequence of the reference homolog. The below function performs this step.

Note 1: we will probably need some special-purpose code to handle gaps. This isn't done yet.

In [11]:
def variant_mutations_wrt_ref(
    func_score_df:pd.DataFrame, 
    homologs:dict,
    homolog_name_col,
    substitution_col
):
    """
    Takes a dataframe for making a `BinaryMap` object, and adds
    a column where each entry is a list of mutations in a variant
    relative to the amino-acid sequence of the reference homolog.
    
    Parameters
    ----------

    func_score_df : pandas.DataFrame
        This should be in the same format as described in BinaryMap.
        
    homologs : dict
        A dictionary containing all possible target homolog 
        names (keys) and sequences (values).
    
    homolog_name_col : str
        The name of the column in func_score_df that identifies the
        homolog for a given variant.
    
    substitution_col: The name of the column in func_score_df that
        lists mutations in each variant relative to the wildtype
        amino-acid sequence of the homolog in which they occur.
    
    Returns
    -------
        
    pd.DataFrame :
        A dataframe with a new column 'var_wrt_ref' that contains
        all variant mutations with respect to the wildtype.
    
    """
    
    def mutations_wrt_ref(mutations, hom_wtseq):
        """
        Takes a list of mutations for a given variant relative
        to its background homolog and returns a list of all
        mutations that separate the variant from the reference
        homolog.
        """
        
        # Compute the full amino-acid sequence of the
        # given variant
        mutated_homolog = list(hom_wtseq)
        for mutation in mutations.split():

            # TODO: Do we need to change the regex to allow
            # for gap '-' and stop '*' characters?
            pattern = r'(?P<aawt>\w)(?P<site>\d+)(?P<aamut>[\w\*])'
            match = re.search(pattern, mutation)
            assert match != None, mutation
            aawt = match.group('aawt')
            site = match.group('site')
            aamut = match.group('aamut')
            mutated_homolog[int(site)-1] = aamut
            
        hom_var_seq = ''.join(mutated_homolog)
        
        # Make a list of all mutations that separate the variant
        # from the reference homolog
        ref_muts = [
            f"{aaref}{i+1}{aavar}" 
            for i, (aaref, aavar) in enumerate(zip(homologs["reference"], hom_var_seq))
            if aaref != aavar
        ]
        
        return " ".join(ref_muts)

    # Duplicate the substitutions_col, then loop over homologs
    # and modify entries as needed
    func_score_df = func_score_df.assign(var_wrt_ref = func_score_df[substitution_col].values)
    for hom_name, hom_seq in homologs.items():
        if hom_name == "reference": continue
        hom_df = func_score_df.query(f"{homolog_name_col} == '{hom_name}'")
        hom_var_wrt_ref = [
            mutations_wrt_ref(muts, homologs[hom_name]) 
            for muts in hom_df[substitution_col]
        ]
        func_score_df.loc[hom_df.index.values, "var_wrt_ref"] = hom_var_wrt_ref
        
    return func_score_df

Next, we will test the above function with a small test case. Below, we define variants from two imaginary homologs: "reference" and "2".

In [12]:
# TODO: right now, the code requires that one of the homologs
# is called "reference". We need to add code to somehow make
# this work with arbitrary input.
homologs = {
    "reference" : "MG",
    "2" : "MP"
}

In [13]:
test_dict = {
    'homolog' : ["reference","reference","reference","2","2","2","2","2"],
    'variant' : ['M1E', 'G2R', 'G2P', 'M1E', 'P2R', 'P2G', 'M1E P2G', 'M1E P2R'],
    'log2E' : [2, -7, -0.5, 2.3, -5, 0.4, 2.7, -2.7],
}
test_df = pd.DataFrame(test_dict)
test_df

homolog  variant  log2E
0  reference      M1E    2.0
1  reference      G2R   -7.0
2  reference      G2P   -0.5
3          2      M1E    2.3
4          2      P2R   -5.0
5          2      P2G    0.4
6          2  M1E P2G    2.7
7          2  M1E P2R   -2.7

In [14]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   homolog  8 non-null      object 
 1   variant  8 non-null      object 
 2   log2E    8 non-null      float64
dtypes: float64(1), object(2)
memory usage: 320.0+ bytes


In [15]:
func_score_df = variant_mutations_wrt_ref(test_df, homologs, "homolog", "variant")
func_score_df

homolog  variant  log2E var_wrt_ref
0  reference      M1E    2.0         M1E
1  reference      G2R   -7.0         G2R
2  reference      G2P   -0.5         G2P
3          2      M1E    2.3     M1E G2P
4          2      P2R   -5.0         G2R
5          2      P2G    0.4            
6          2  M1E P2G    2.7         M1E
7          2  M1E P2R   -2.7     M1E G2R

Next, we will use the modified dataframe to create a `BinaryMap` object for each homolog. Each object needs to have the exact same columns in the same order. To achieve this, we will first make a list of all unique mutations observed in the above dataframe.

In [16]:
allowed_subs = {
    s for subs in func_score_df.var_wrt_ref
    for s in subs.split()
}
allowed_subs

{'G2P', 'G2R', 'M1E'}

Then, we will make a `BinaryMap` for each homolog, feeding the above list to the function that makes the maps, which ensures the maps will have identical columns.

In [17]:
X = {}
for homolog, homolog_func_score_df in func_score_df.groupby("homolog"):
    ref_bmap = bmap.BinaryMap(
        homolog_func_score_df,
        substitutions_col="var_wrt_ref",
        allowed_subs=allowed_subs
    )
    
    # TODO use sparse arrays
#     X[homolog] = jnp.array(ref_bmap.binary_variants.toarray())
    X[homolog] = sparse.BCOO.fromdense(ref_bmap.binary_variants.toarray())
    
    print(homolog)
    print(ref_bmap.binary_variants.toarray())
    print({mut:ref_bmap.sub_to_i(mut) for mut in allowed_subs})

2
[[1 1 0]
 [0 0 1]
 [0 0 0]
 [1 0 0]
 [1 0 1]]
{'M1E': 0, 'G2P': 1, 'G2R': 2}
reference
[[1 0 0]
 [0 0 1]
 [0 1 0]]
{'M1E': 0, 'G2P': 1, 'G2R': 2}


## Implementing the full model with JAX

Below, we implement the $\phi$ and $g$ functions from above.

Next, we initialize values of free parameters for downstream optimization by JAX.

In [18]:
# all model params to be tuned will be stored in a dictionary
params = {}
seed = 0
key = jax.random.PRNGKey(seed)

# initialize beta parameters from normal distribution.
all_mutations = list(allowed_subs)
params["β"] = jax.random.normal(shape=(len(all_mutations),), key=key)

# initialize shift parameters
# TODO no need for subkeys
key, *subkeys = jax.random.split(key, len(homologs)+1)
for homolog, subkey in zip(homologs, subkeys):
    
    # Do not create shift parameters for the reference
#     if homolog == "reference": continue
    
    # We expect most shift parameters to be close to zero
    params[f"S_{homolog}"] = jnp.zeros(shape=(len(all_mutations),))

params["C_ref"] = jnp.zeros(shape=(1, ))

# Number of free parameters for a linear transformation on the latent phenotype
# that results in the shape of the sigmoid.
n_units = 1

# TODO ??: Are we parameterizing out GE function correctly?
key, *subkeys = jax.random.split(key, num=5)
params["α"]=dict(sig_stretch_x = jax.random.normal(shape=(n_units,), key=subkeys[0]), # 'stretch' in x direction
                 sig_shift_x = jax.random.normal(shape=(1,), key=subkeys[1]),         # 'shift' in the x direction
                 sig_stretch_y = jax.random.normal(shape=(n_units,), key=subkeys[2]),       # 'stretch' in the y direction
                 sig_shift_y = jax.random.normal(shape=(1,), key=subkeys[3]),         # 'shift' in the y directions
)

params

{'β': DeviceArray([ 0.18784401, -1.28334229,  0.6494182 ], dtype=float64),
 'S_reference': DeviceArray([0., 0., 0.], dtype=float64),
 'S_2': DeviceArray([0., 0., 0.], dtype=float64),
 'C_ref': DeviceArray([0.], dtype=float64),
 'α': {'sig_stretch_x': DeviceArray([0.55893636], dtype=float64),
  'sig_shift_x': DeviceArray([1.70016778], dtype=float64),
  'sig_stretch_y': DeviceArray([1.31402346], dtype=float64),
  'sig_shift_y': DeviceArray([-0.45297973], dtype=float64)}}

Format the data to be fed into the model

In [19]:
y = {h:jnp.array(hfdf.log2E.values) for h, hfdf in func_score_df.groupby("homolog")}
data = (X, y)
data

({'2': BCOO(int8[5, 3], nse=6), 'reference': BCOO(int8[3, 3], nse=3)},
 {'2': DeviceArray([ 2.3, -5. ,  0.4,  2.7, -2.7], dtype=float64),
  'reference': DeviceArray([ 2. , -7. , -0.5], dtype=float64)})

Define an objective function to optimize

In [20]:
# TODO centering wildtype -
# TODO static args for reference -
# TODO regularization -

@jax.jit
def ϕ(params:dict, X_h:jnp.array):
    """Model for predicting latent space"""
    
    return (X_h @ (params["β"] + params[f"S"])) + params["C_ref"]


@jax.jit
def g(α:dict, z_h:jnp.array):
    """Model for global epistasis as 'flexible' sigmoid."""
     
    activations = jax.nn.sigmoid(α["sig_stretch_x"] * z_h[:, None] + α["sig_shift_x"])
#     wt_activations = jax.nn.sigmoid(α["sig_stretch_x"] * α["C_ref"] + α["sig_shift_x"])
#     activations -= wt_activations
    return (α["sig_stretch_y"] * activations) + α["sig_shift_y"] # sig shift y needs to be 0 for the reference


@jax.jit
def cost_smooth(params, data, δ=1):
    """Cost (Objective) function as a sum of huber loss across all homologs"""

    
#     print("Calling Cost Function", flush=True)
    X, y = data
    loss = 0
    
    
    # Sum the huber loss across all homologs
    for homolog, X_h in X.items():
        
        # Fix the shift parameters for reference to 0
        # Static arguments for reference params?
        S_h = jnp.where(
            homolog=="reference", 
            jnp.zeros(len(params['β'])), 
            params[f"S_{homolog}"]
        )
        
        # Subset the params being passed into latent prediction, ϕ
        h_params = {"β":params["β"], "S":S_h, "C_ref":params["C_ref"]}
        
#         print(f"Calling Phi Function {homolog}", flush=True)
        z_h = ϕ(h_params, X_h)
        
        # Pass the latent predictions through GE model prediction
        # all GE specific parameters are stored in α
#         print(f"Calling G Function {homolog}", flush=True)
        y_h_predicted = g(params["α"], z_h)
        
        # compute loss at current parameter state.
        loss += jaxopt.loss.huber_loss(y[homolog], y_h_predicted, δ).mean()

#     print(f"{loss}", flush=True)
    return loss

Calculate initial loss with random parameters

In [21]:
cost_smooth(params, data)

DeviceArray(5.02411651, dtype=float64)

In [22]:
tol = 1e-6
maxiter = 1000
solver = jaxopt.GradientDescent(cost_smooth, tol=tol, maxiter=maxiter)

In [23]:
params, state = solver.run(params, data=data)

Optimize the entire model at once with gradient decent

Peek at tuned parameters

In [24]:
params

{'C_ref': DeviceArray([-0.72320785], dtype=float64),
 'S_2': DeviceArray([2.63420862, 2.63523184, 2.59795679], dtype=float64),
 'S_reference': DeviceArray([0., 0., 0.], dtype=float64),
 'α': {'sig_shift_x': DeviceArray([0.69421427], dtype=float64),
  'sig_shift_y': DeviceArray([-0.5059075], dtype=float64),
  'sig_stretch_x': DeviceArray([2.06062493], dtype=float64),
  'sig_stretch_y': DeviceArray([2.91412947], dtype=float64)},
 'β': DeviceArray([-2.63421577, -2.63523528, -2.59796787], dtype=float64)}

## Simulation Fit

In [43]:
simulated_dataset = pd.read_csv("results/simulated_dataset_v1.csv")

In [44]:
import json
homologs = json.load(open("results/homolog_aa_seqs.json", "r"))

In [45]:
homologs["reference"] = homologs['1']
homologs["H2"] = homologs['2']
del homologs['1']
del homologs['2']
homologs

{'reference': 'RSVILRAYTNSRVKRVILCNNDLPIRNIRLMMILHNSDASFSTPVGLRSG',
 'H2': 'RVVILRAYTNSRVKRIKLCNNDRPIRNIRTMMIEHNSDAKFHTPYGLDSG'}

In [47]:
simulated_dataset_lib1 = simulated_dataset.query("library == 'lib_1'").copy()
simulated_dataset_lib1.aa_substitutions.fillna("", inplace=True)
simulated_dataset_lib1 = simulated_dataset_lib1.sample(n=1000)

In [48]:
func_score_df = variant_mutations_wrt_ref(simulated_dataset_lib1, homologs, "homolog", "aa_substitutions")
func_score_df

library           barcode  variant_call_support  \
2983    lib_1  ACTTAACCCGCTGGTC                     6   
11344   lib_1  CTCCAGCGATTTTGCT                     4   
8064    lib_1  CCATGGTGAACACCGT                     3   
22871   lib_1  TGGGAACACTTTTGTG                     2   
55304   lib_1  ATCGGACGTTGTGAAT                     2   
...       ...               ...                   ...   
15024   lib_1  GCGGAAACACTTGGGT                     2   
73952   lib_1  TTCCACCGATTGATGC                    10   
11321   lib_1  CTCATTACACAAACAC                     6   
59130   lib_1  CCTGCCGGTGGTACAC                     2   
17536   lib_1  GTATCACGCCGAGAGT                     4   

                              codon_substitutions    aa_substitutions  \
2983                             CTG5CCC ATC25TCC            L5P I25S   
11344                                    ATC33CAG                I33Q   
8064                   TTA18CAG CGC26GGC GGT46CAG      L18Q R26G G46Q   
22871                           AAC27CAT GCT39AGC           N27H A39S   
55304                  CCT24TCC ATC33AGG GAC38TCT      P24S I33R D38S   
...                                           ...                 ...   
15024                           GAC22AAC ATG31CAG           D22N M31Q   
73952                  ATA16TTT TGC19GCC AAC27TCT      I16F C19A N27S   
11321  AGA1AGG ATT4ACA TCA11AAA ATC33GAA AGT40AAG  I4T S11K I33E S40K   
59130                            GTG3ATT GGT46CGT            V3I G46R   
17536                                    GTA45CTC                V45L   

       n_codon_substitutions  n_aa_substitutions  latent_phenotype  \
2983                       2                   2          1.539948   
11344                      1                   1          3.184927   
8064                       3                   3         -7.220225   
22871                      2                   2         -7.055652   
55304                      3                   3         -7.432658   
...                      ...                 ...               ...   
15024                      2                   2          0.876896   
73952                      3                   3         -9.959286   
11321                      5                   4        -18.095718   
59130                      2                   2        -10.247332   
17536                      1                   1          4.675558   

       observed_phenotype  observed_enrichment    homolog  \
2983            -0.270249             0.829177  reference   
11344           -0.048761             0.966767  reference   
8064            -9.170605             0.001735  reference   
22871           -9.065282             0.001867  reference   
55304           -9.294194             0.001593         H2   
...                   ...                  ...        ...   
15024           -0.491620             0.711226  reference   
73952           -9.898959             0.001047         H2   
11321           -9.965764             0.001000  reference   
59130           -9.915395             0.001036         H2   
17536           -0.003692             0.997444  reference   

                                             var_wrt_ref  
2983                                            L5P I25S  
11344                                               I33Q  
8064                                      L18Q R26G G46Q  
22871                                          N27H A39S  
55304  S2V V16I I17K L23R P24S L30T I33R L34E D38S S4...  
...                                                  ...  
15024                                          D22N M31Q  
73952  S2V V16F I17K C19A L23R N27S L30T L34E S40K S4...  
11321                                 I4T S11K I33E S40K  
59130  S2V V3I V16I I17K L23R L30T L34E S40K S42H V45...  
17536                                               V45L  

[1000 rows x 12 columns]

Next, we will use the modified dataframe to create a `BinaryMap` object for each homolog. Each object needs to have the exact same columns in the same order. To achieve this, we will first make a list of all unique mutations observed in the above dataframe.

In [49]:
allowed_subs = {
    s for subs in func_score_df.var_wrt_ref
    for s in subs.split()
}
# allowed_subs

Then, we will make a `BinaryMap` for each homolog, feeding the above list to the function that makes the maps, which ensures the maps will have identical columns.

In [50]:
X = {}
for homolog, homolog_func_score_df in func_score_df.groupby("homolog"):
    ref_bmap = bmap.BinaryMap(
        homolog_func_score_df,
        substitutions_col="var_wrt_ref",
        allowed_subs=allowed_subs
    )
    
    # TODO use sparse arrays
#     X[homolog] = jnp.array(ref_bmap.binary_variants.toarray())
    X[homolog] = sparse.BCOO.fromdense(ref_bmap.binary_variants.toarray())
    
    
    print(homolog)
    print(ref_bmap.binary_variants.toarray())
#     print({mut:ref_bmap.sub_to_i(mut) for mut in allowed_subs})

H2
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
reference
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [51]:
y = {h:jnp.array(hfdf.observed_enrichment.values) for h, hfdf in func_score_df.groupby("homolog")}
data = (X, y)
data

({'H2': BCOO(int8[513, 797], nse=5867),
  'reference': BCOO(int8[487, 797], nse=981)},
 {'H2': DeviceArray([1.59282808e-03, 4.02919846e-01, 5.13124380e-01,
               1.00000000e+00, 1.00000008e-03, 1.15836403e-02,
               1.00000000e+00, 1.00000000e+00, 1.00309481e+00,
               2.05467841e-02, 1.00018728e-03, 9.87902053e-01,
               8.80478856e-01, 2.90758904e-01, 1.00000000e+00,
               7.95061472e-01, 2.29435861e-03, 3.35428206e-01,
               1.00000000e+00, 1.07689708e-03, 7.75178352e-03,
               4.45521931e-02, 1.00000000e-03, 3.24549822e-03,
               8.26960999e-02, 8.69042346e-01, 8.33343671e-03,
               1.00333967e+00, 1.00000793e-03, 1.00000003e-03,
               1.00501774e-03, 4.17414882e-03, 1.00000000e+00,
               1.00000092e-03, 7.54715746e-01, 1.00000001e-03,
               2.46038184e-01, 9.95925579e-01, 1.00080727e-03,
               1.00000000e+00, 1.00007366e-03, 1.00000048e-03,
               1.00003690

In [52]:
# all model params to be tuned will be stored in a dictionary
params = {}
seed = 0
key = jax.random.PRNGKey(seed)

# initialize beta parameters from normal distribution.
all_mutations = list(allowed_subs)
params["β"] = jax.random.normal(shape=(len(all_mutations),), key=key)

# initialize shift parameters
# TODO no need for subkeys
key, *subkeys = jax.random.split(key, len(homologs)+1)
for homolog, subkey in zip(homologs, subkeys):
    
    # Do not create shift parameters for the reference
#     if homolog == "reference": continue
    
    # We expect most shift parameters to be close to zero
    params[f"S_{homolog}"] = jnp.zeros(shape=(len(all_mutations),))

params["C_ref"] = jnp.zeros(shape=(1, ))

# Number of free parameters for a linear transformation on the latent phenotype
# that results in the shape of the sigmoid.
n_units = 1

# TODO ??: Are we parameterizing out GE function correctly?
key, *subkeys = jax.random.split(key, num=5)
params["α"]=dict(sig_stretch_x = jax.random.normal(shape=(n_units,), key=subkeys[0]), # 'stretch' in x direction
                 sig_shift_x = jax.random.normal(shape=(1,), key=subkeys[1]),         # 'shift' in the x direction
                 sig_stretch_y = jax.random.normal(shape=(n_units,), key=subkeys[2]),       # 'stretch' in the y direction
                 sig_shift_y = jax.random.normal(shape=(1,), key=subkeys[3]),         # 'shift' in the y directions
)

params.keys()

dict_keys(['β', 'S_reference', 'S_H2', 'C_ref', 'α'])

In [53]:
params['β'].shape

(797,)

In [54]:
cost_smooth(params, data)

DeviceArray(0.51139129, dtype=float64)

In [55]:
# cost_deriv = jax.grad(cost_smooth)

In [56]:
tol = 1e-6
maxiter = 10
solver = jaxopt.GradientDescent(cost_smooth, tol=tol, maxiter=maxiter)

In [57]:
params, state = solver.run(params, data=data)

Optimize the entire model at once with gradient decent

Peek at tuned parameters

In [58]:
params

{'C_ref': DeviceArray([0.00849814], dtype=float64),
 'S_H2': DeviceArray([ 6.33856598e-05,  1.42714460e-04,  6.76662101e-05,
               6.81472685e-05,  0.00000000e+00,  0.00000000e+00,
               1.87292113e-04,  0.00000000e+00,  6.80411549e-05,
               0.00000000e+00,  6.57559382e-05,  3.12434337e-05,
               1.68026249e-04,  3.40705517e-04,  6.39440653e-05,
               1.42791550e-04,  0.00000000e+00,  0.00000000e+00,
               1.12685584e-04,  6.33856598e-05,  7.31657325e-05,
               6.83290358e-05,  0.00000000e+00,  7.30480295e-05,
               0.00000000e+00,  0.00000000e+00,  7.24421144e-05,
               7.27784576e-05,  1.40409238e-04,  2.04684554e-04,
              -2.13534531e-05,  3.28089726e-02,  0.00000000e+00,
               1.41277004e-04,  6.52346689e-05,  0.00000000e+00,
               0.00000000e+00,  6.86450664e-05,  0.00000000e+00,
               0.00000000e+00,  1.33099789e-04,  0.00000000e+00,
               1.37396424e-04,

## Empirical Data (TODO)

In [2]:
df = pd.read_csv("https://media.githubusercontent.com/media/jbloomlab/SARS-CoV-2-RBD_DMS_Omicron/main/results/binding_Kd/bc_binding.csv")

In [3]:
df

library           barcode      target    variant_class  \
0       pool1A  AAAAAAAAAAACGCGA         BA2  1 nonsynonymous   
1       pool1A  AAAAAAAAAAAGGAGA  Wuhan_Hu_1  1 nonsynonymous   
2       pool1A  AAAAAAAAAAATTTAA  Wuhan_Hu_1         wildtype   
3       pool1A  AAAAAAAAAACAAAAA         BA1  1 nonsynonymous   
4       pool1A  AAAAAAAAAACGCGTA  Wuhan_Hu_1  1 nonsynonymous   
...        ...               ...         ...              ...   
598389  pool2A  TTTTTTTGATATTGGA  Wuhan_Hu_1  1 nonsynonymous   
598390  pool2A  TTTTTTTGCTCTTACC         BA1  1 nonsynonymous   
598391  pool2A  TTTTTTTGTATAACAA         BA1  1 nonsynonymous   
598392  pool2A  TTTTTTTTAGCCGATA         BA2  1 nonsynonymous   
598393  pool2A  TTTTTTTTGATAGAAA         BA1  1 nonsynonymous   

       aa_substitutions  n_aa_substitutions  TiteSeq_avgcount   log10Ka  
0                  I88V                   1          3.317373       NaN  
1                 G166M                   1         59.823342  5.963056  
2                   NaN                   0         66.484153  8.913236  
3                  A42N                   1         17.062794  9.253828  
4                 E154T                   1         24.911126  9.152625  
...                 ...                 ...               ...       ...  
598389            C158G                   1         47.587851  5.000000  
598390            S129P                   1         63.491459  8.837559  
598391            P191W                   1         22.825324  8.992898  
598392             F17T                   1         93.332943  7.592250  
598393             L60P                   1         21.842079  8.605169  

[598394 rows x 8 columns]

## Old code Attic

In [ ]:
# @jax.jit
# def ϕ(params:dict, X_tuple:tuple): #X_h:jnp.array): #, homolog:str):#is_ref:bool):
#     """Phi function for predicting latent phenotype."""
    
    
    
# #     if is_ref:
#     homolog = X_tuple[0]
#     X_h = X_tuple[1]
#     if homolog == "reference":
        
#         return (X_h @ params["β"]) + params["C_ref"]

#     return (X_h @ (params["β"] + params[f"S_{homolog}"])) + params["C_ref"]

# @jax.jit
# def ϕ(params:dict, X_h:jnp.array):
#     return (X_h @ (params["β"] + params[f"S"])) + params["C_ref"]

# @jax.jit
# def g(α:dict, z_h:jnp.array):
#     """Global epistasis function as flexible sigmoid."""
#     activations = jax.nn.sigmoid(α["rate"] * z_h[:, None] + α["intercept"])
#     return (α["a"] * activations) + α["bias"] 